const UserActionTypes = {
    SET_CURRENT_USER_START: "SET_CURRENT_USER_START",
    SET_CURRENT_USER_SUCCESS: "SET_CURRENT_USER_SUCCESS",
    SET_CURRENT_USER_FAILURE: "SET_CURRENT_USER_FAILURE"
};

export default UserActionTypes;